#!/bin/bash
oPWD="$(pwd)"
cd /tmp

apt-get install -y liborc-0.4-dev 
git clone https://github.com/ghostop14/gr-correctiq
cd gr-correctiq
git checkout maint-3.8
mkdir build
cd build
cmake ../
make
make install
ldconfig

cd "$oPWD"